version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/vue/test
    steps:
      - checkout
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - node-10-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - node-10-dependencies-
      - run:
          name: yarn install
          command: yarn install && yarn global add firebase && yarn global add firebaseui && yarn global add firebaseui-ja && yarn global add moment && yarn global add node-gyp && yarn global add moment && yarn global add @vue/cli
      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package.json" }}
      - run:
          name: yarn test
          command: yarn test
      - run:
          name: yarn build
          command: yarn build
