version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/vue/test
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install && yarn global add firebase && yarn global add firebaseui && yarn global add firebaseui-ja && yarn global add moment && yarn global add node-gyp && yarn global add moment && yarn global add @vue/cli && yarn global add vue2-google-maps && yarn global add vue-loading-overlay
      - save_cache:
          name: save_cache
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package.json" }}
      - run:
          name: yarn lint
          command: yarn lint
      - run:
          name: yarn test
          command: yarn test
# EC2にSSH接続し、ビルド、コンテナを実行
  build:
    machine:
      image: circleci/classic:edge
    steps:
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
            - "68:76:75:bf:2f:99:83:88:c3:9b:54:6d:b1:d1:5e:49"
      - run:
          name: ssh test
          command: ssh ${USER_NAME}@${HOST_NAME} 'echo "CircleCI SSH Test"'
      - run:
          name: git pull
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/vue-docker/app && git pull origin master && sudo rm -rf node_modules'
          when: always
      - run:
          name: docker rm vue
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker stop vue_portfolio ; docker rm vue_portfolio'
          when: always
      - run:
          name: docker rmi image
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker rmi -f docker-portfolio_vueapp'
          when: always
      - run:
          name: docker compose
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker-compose up -d'
          when: always
      - run:
          name: yarn install
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker exec vue_portfolio yarn install'
          when: always
      - run:
          name: yarn build
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker exec vue_portfolio yarn build'
          when: always
      - run:
          name: yarn start
          command: ssh ${USER_NAME}@${HOST_NAME} 'ssh -i "portfolio_key.pem" ec2-user@${PRIVATE_SUBNET} && cd /work/docker-portfolio/ && docker exec vue_portfolio yarn start &'
          when: always
workflows:
    version: 2
    test_and_build:
        jobs:
            - test
            - build:
                requires:
                    - test
                filters:
                    branches:
                        only: master
