version: 2
defaults: &defaults
  working_directory: ~/aws-rough
  docker:
    - image: circleci/python:3.6-jessie-node-browsers
filter_only_master: &filter_only_master
  filters:
    branches:
      only: master
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - ./*
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: yarn build
      - persist_to_workspace:
          root: ~/aws-rough
          paths:
            - release

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/aws-rough
      - run: sudo pip install awscli
      - run: aws s3 sync ./release/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws s3 sync ./release/ s3://aws.noplan.cc --exact-timestamps --delete --exclude "*" --include "*.js" --cache-control max-age=31536000

workflows:
  version: 2
  test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          <<: *filter_only_master
          requires:
            - install
            - test
      - deploy:
          <<: *filter_only_master
          requires:
            - install
            - test
            - build
